// src/client/app/react/components/title.js
import { Text } from 'react-elemental';
import React from 'react';

const Title = () => (
  <div>
    <Text size="40px" margin="20%" bold uppercase center>
      Valorant
    </Text>
    <Text size="20px" center>
      Utility line ups for all the agents
    </Text>
  </div>
);

export default Title;

// src/components/Title.vue
<template>
  <div class="container">
    <div class="title">
      Valorant
    </div>
    <div class="subtitle">
      A breakdown of agent utility lineups
    </div>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class Title extends Vue {}
</script>
<style scoped lang="scss">
.container {
  text-align: center;
}
.title {
  font-weight: bold;
  font-size: 40px;
  margin-bottom: 2%;
}
</style>
